# Chris Arnold
# Advertising Success Predictor

# Bayesian Network originally generated by naiveBayes machine
# learning algorithm from R library "e1071".

advertisingPredictor <- function(advProdTemp, advProdHealth){
  # Probability of boughtAdv given adProdTemp and advProdHealth
  # predicted using Bayes theorem with assumption of independent
  # inputs for simplification
  
  # P( boughtAdv | advProdTemp, advProdHealth) =
  # aPriori-P(boughtAdv) * P(advTemp | boughtAdv) * P(advHealth | boughtAdv)
  # / ( P(advTemp) * P(advHealth) )
  
  # aPriori-P(boughtAdv) 0.3153816
  
  return((0.3153816
          *advProdTempCPT(advProdTemp)
          *advProdHealthCPT(advProdHealth)))
 
}

# P ( advTemp | boughtAdv)
advProdTempCPT <- function(advProdTemp){
  if(advProdTemp == "Cold"){
    return(0.3627914)
  }else{
    return(0.6372086)
  }
}

# P ( advHealth | boughtAdv)
advProdHealthCPT <- function(advProdHealth){
  if(advProdHealth == "Healthy"){
    return(0.5745117)
  }else{
    return(0.4254883)
  }
}